//  ARRAY DE OBJETOS
let 
let aluno ={
    Nome: 'Manases B',
    Idade:'12',
    Altura:'1.56',
    isCracha: true,
    isCamisa: false,
    isPaciencia: true,
    isChora: true,
    cor: 'Bege',
    notas: [10, 8, 9, 7, 5.5, 6.5]
    //      0   1  2  3   4    5
}

// transformar o obj em JSON
console.log(aluno)

console.log(JASON.stringify(aluno))

let Jasonito = '{
    '




















// // RETORNAR O OBJETO
// console.log(aluno)

// // RETORNA APENAS O NOME
// console.log(aluno.Nome)

// // RETORNA APENAS O CAMPO ISCHORA
// console.log(aluno.isChora)

// // RETORNA APENAS O NOME
// console.log('O aluno é ${aluno.Nome}')

// for(i = 0; < IOS.length; i++){
//     let login =IOS[i]
//     if(login..isCracha ==true){
//         console.log("O aluno tem cracha")
//         console.log(login.isCracha)
//     }else{
//         console.log("Aluno não tem cracha")
//     }
// }