// Array - Metodo forEach
let frutas = [ // COLOQUE O NOME DE 8 FRUTAS
    "Morango",
    "uva",
    "maçã",
    "manga",
    "abacaixi",
    "laranja",
    "banana",
    "melão"
] 

frutas.forEach(Percorrer)

function Percorrer(valor, indece){
    
}
function Percorrer(valor, indece)

// for{i =0; i <= frutas.length ; i++{
    // console.log(frutas);[i]; // CONTEUDO DA POIÇÃO
    // console.log(i); // NUMERO DA POSIÇÃO
}

}

